### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by peymanshahmarimikaeeldarehsi** [bermarte/js-quiz#5]

**Comment by peymanshahmarimikaeeldarehsi** [comment]
issue for questions

**Comment by bermarte** [comment]
You should write a bit of text, an explanation and the different steps you did, something like this:

- [X] Adding questions to the JSON file
- [X] Searching links for documentation
this user story is created in a branch called `questions`

then you should create a milestone and maybe link this issue to your pull request

**Comment by bermarte** [comment]
There is no description;

**Comment by bermarte** [comment]
@peyman I asked you to change one question (:
There were some errors in the questions.

**Comment by peyman** [comment]
> @peyman I asked you to change one question (:
> There were some errors in the questions.

@bermarte @peymanshahmarimikaeeldarehsi 
Wrong handle guys. I am not involved in this project.
Cheers.
